# Generated by Django 5.2.6 on 2025-10-20 17:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('max_id_number', models.PositiveIntegerField(default=14, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_phone_number', models.PositiveIntegerField(default=11, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the payment method (e.g., Visa, Cash)', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duration_days', models.IntegerField(help_text='Duration of the subscription in days.')),
                ('allowed_accounts', models.PositiveIntegerField(default=5, help_text='Total number of Doctor/Reception accounts allowed.')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SITE_OWNER', 'Site Owner'), ('CLINIC_OWNER', 'Clinic Owner'), ('DOCTOR', 'Doctor'), ('RECEPTION', 'Reception')], db_index=True, default='RECEPTION', max_length=50),
        ),
        migrations.CreateModel(
            name='ClinicOwnerProfile',
            fields=[
                ('user', models.OneToOneField(limit_choices_to={'role': 'CLINIC_OWNER'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='clinic_owner_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('clinic_owner_name', models.CharField(max_length=255)),
                ('clinic_name', models.CharField(max_length=255)),
                ('owner_phone_number', models.CharField(max_length=20)),
                ('clinic_phone_number', models.CharField(max_length=20)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('tiktok', models.URLField(blank=True, null=True)),
                ('gmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('INACTIVE', 'Inactive'), ('ACTIVE', 'Active'), ('ENDED', 'Ended'), ('SUSPENDED', 'Suspended')], db_index=True, default='INACTIVE', max_length=20)),
                ('added_by', models.ForeignKey(limit_choices_to={'role': 'SITE_OWNER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clinics', to=settings.AUTH_USER_MODEL)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinics', to='accounts.country')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('user', models.OneToOneField(limit_choices_to={'role': 'DOCTOR'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='doctor_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('clinic_owner_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='accounts.clinicownerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ReceptionProfile',
            fields=[
                ('user', models.OneToOneField(limit_choices_to={'role': 'RECEPTION'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='reception_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('clinic_owner_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptionists', to='accounts.clinicownerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_accounts_number', models.PositiveIntegerField(default=0)),
                ('ref_number', models.CharField(blank=True, max_length=100)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comments', models.TextField(blank=True)),
                ('activation_date', models.DateField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, db_index=True)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('ACTIVE', 'Active'), ('ENDED', 'Ended'), ('SUSPENDED', 'Suspended')], db_index=True, default='UPCOMING', max_length=20)),
                ('activated_by', models.ForeignKey(limit_choices_to={'role': 'SITE_OWNER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_history', to='accounts.clinicownerprofile')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.paymentmethod')),
                ('subscription_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.subscriptiontype')),
            ],
        ),
    ]
